### ISSUE TITLE
Is this the new home for mpt-status?

### ISSUE THREAD

**Issue by petterreinholdtsen** [baruch/mpt-status#2]
I was just looking at the Debian package for mpt-status, https://tracker.debian.org/pkg/mpt-status, and noticed no upstream link was provided there.  Is this the new upstream home for mpt-status?  The original download site was http://www.drugphish.ch/~ratz/mpt-status/, but those pages are no longer present.

Note, the Debian package got three patches you might want to consider including in a new release of mpt-status.

**Comment by baruch** [comment]
I created this for myself to save some patches IIRC, out of the three patches I think that only one applies in general and the other two are debian specific. The general one is already part of this repository and it was contributed potentially by the debian packager.

As I don't have the relevant hardware anymore I wouldn't be a good caretaker. Anyone else who fancies should pick this up and take it.

**Comment by petterreinholdtsen** [comment]
[Baruch Even]
> I created this for myself to save some patches IIRC, out of the three
> patches I think that only one applies in general and the other two are
> debian specific. The general one is already part of this repository
> and it was contributed potentially by the debian packager.

Right.

> As I don't have the relevant hardware anymore I wouldn't be a good
> caretaker. Anyone else who fancies should pick this up and take it.

I do not have the hardware either.  My role is this is just brushing up
the currently orphaned package in Debian, moving the packaging source to
git and try to push patches upstream.

-- 
Happy hacking
Petter Reinholdtsen
